services:
  frontend:
    image: example/webapp
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
